to fix connect ECONNREFUSED 127.0.0.1

diff --git a/.github/workflows/otc_ci_6.yml b/.github/workflows/otc_ci_6.yml
--- a/.github/workflows/otc_ci_6.yml
+++ b/.github/workflows/otc_ci_6.yml
@@ -103,7 +103,7 @@ jobs:
 
     - name: Check backend user endpoint
       run: |
-        wget -qO- http://127.0.0.1:30080/user/all-users
+        curl -f http://127.0.0.1:30080/user/all-users || echo "Failed to reach /user/all-users"
 
     - name: Run Newman Tests
       run: |
